### ISSUE TITLE
Train error with SOP

### ISSUE THREAD

**Issue by Arrebol2020** [elias-ramzi/ROADMAP#6]
Hi, I ran the training in SOP, model is resnet, when it computing accuracy for the test split w.r.t ['test'], I got this error:
> Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:162; details: cublas failed (13): (512, 512) x (60502, 512)' = (512, 60502)
Aborted

**Comment by Arrebol2020** [comment]
It seems that the error occur beacause the follow in roadmap/engine/get_knn.py get_knn_faiss():
```
co = faiss.GpuMultipleClonerOptions()
co.shards = True
index = faiss.index_cpu_to_all_gpus(index, co) 
```
I annotate it, and it works.

**Comment by elias-ramzi** [comment]
Hi !
Sorry for the late response I was not at work.

Glad you could figure out what was wrong.

Did you ran the code with multiple GPU's ?
I will try to fix it.
